services:
  - type: web
    name: invoicedesk
    runtime: docker
    plan: free
    envVars:
      - key: IS_RENDER
        value: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: invoicedesk-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: invoicedesk-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: invoicedesk-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: invoicedesk-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: invoicedesk-db
          property: password
      - key: APP_URL
        value: https://invoicedesk.onrender.com
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: bhargavpatel0580@gmail.com
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: bhargavpatel0580@gmail.com
      - key: EMAILJS_SERVICE_ID
        value: service_p9kug5r
      - key: EMAILJS_TEMPLATE_ID
        value: template_p5g316q
      - key: EMAILJS_PUBLIC_KEY
        value: Bj0pRNasz5WltnwWw
      - key: EMAILJS_PRIVATE_KEY
        sync: false

databases:
  - name: invoicedesk-db
    plan: free
    databaseName: invoicedesk
    user: invoicedesk_user
