services:
  - type: web
    name: invoicedesk
    runtime: docker
    plan: free
    preDeployCommand: php artisan migrate --force
    envVars:
      - key: IS_RENDER
        value: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: invoicedesk-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: invoicedesk-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: invoicedesk-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: invoicedesk-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: invoicedesk-db
          property: password

databases:
  - name: invoicedesk-db
    plan: free
    databaseName: invoicedesk
    user: invoicedesk_user
